# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from app.protos import bank_account_pb2 as app_dot_services_dot_bank__account_dot_bank__account__pb2


class BankAccountStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.get_all = channel.unary_unary(
                '/BankAccount/get_all',
                request_serializer=app_dot_services_dot_bank__account_dot_bank__account__pb2.BankAccountEmpty.SerializeToString,
                response_deserializer=app_dot_services_dot_bank__account_dot_bank__account__pb2.BankAccountMultipleResponse.FromString,
                )
        self.save = channel.unary_unary(
                '/BankAccount/save',
                request_serializer=app_dot_services_dot_bank__account_dot_bank__account__pb2.BankAccountNotIdRequest.SerializeToString,
                response_deserializer=app_dot_services_dot_bank__account_dot_bank__account__pb2.BankAccountResponse.FromString,
                )
        self.update = channel.unary_unary(
                '/BankAccount/update',
                request_serializer=app_dot_services_dot_bank__account_dot_bank__account__pb2.BankAccountRequest.SerializeToString,
                response_deserializer=app_dot_services_dot_bank__account_dot_bank__account__pb2.BankAccountResponse.FromString,
                )
        self.delete = channel.unary_unary(
                '/BankAccount/delete',
                request_serializer=app_dot_services_dot_bank__account_dot_bank__account__pb2.BankAccountIdRequest.SerializeToString,
                response_deserializer=app_dot_services_dot_bank__account_dot_bank__account__pb2.BankAccountResponse.FromString,
                )


class BankAccountServicer(object):
    """Missing associated documentation comment in .proto file."""

    def get_all(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def save(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def update(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def delete(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_BankAccountServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'get_all': grpc.unary_unary_rpc_method_handler(
                    servicer.get_all,
                    request_deserializer=app_dot_services_dot_bank__account_dot_bank__account__pb2.BankAccountEmpty.FromString,
                    response_serializer=app_dot_services_dot_bank__account_dot_bank__account__pb2.BankAccountMultipleResponse.SerializeToString,
            ),
            'save': grpc.unary_unary_rpc_method_handler(
                    servicer.save,
                    request_deserializer=app_dot_services_dot_bank__account_dot_bank__account__pb2.BankAccountNotIdRequest.FromString,
                    response_serializer=app_dot_services_dot_bank__account_dot_bank__account__pb2.BankAccountResponse.SerializeToString,
            ),
            'update': grpc.unary_unary_rpc_method_handler(
                    servicer.update,
                    request_deserializer=app_dot_services_dot_bank__account_dot_bank__account__pb2.BankAccountRequest.FromString,
                    response_serializer=app_dot_services_dot_bank__account_dot_bank__account__pb2.BankAccountResponse.SerializeToString,
            ),
            'delete': grpc.unary_unary_rpc_method_handler(
                    servicer.delete,
                    request_deserializer=app_dot_services_dot_bank__account_dot_bank__account__pb2.BankAccountIdRequest.FromString,
                    response_serializer=app_dot_services_dot_bank__account_dot_bank__account__pb2.BankAccountResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'BankAccount', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class BankAccount(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def get_all(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/BankAccount/get_all',
            app_dot_services_dot_bank__account_dot_bank__account__pb2.BankAccountEmpty.SerializeToString,
            app_dot_services_dot_bank__account_dot_bank__account__pb2.BankAccountMultipleResponse.FromString,
            options, channel_credentials,
            call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def save(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/BankAccount/save',
            app_dot_services_dot_bank__account_dot_bank__account__pb2.BankAccountNotIdRequest.SerializeToString,
            app_dot_services_dot_bank__account_dot_bank__account__pb2.BankAccountResponse.FromString,
            options, channel_credentials,
            call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def update(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/BankAccount/update',
            app_dot_services_dot_bank__account_dot_bank__account__pb2.BankAccountRequest.SerializeToString,
            app_dot_services_dot_bank__account_dot_bank__account__pb2.BankAccountResponse.FromString,
            options, channel_credentials,
            call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def delete(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/BankAccount/delete',
            app_dot_services_dot_bank__account_dot_bank__account__pb2.BankAccountIdRequest.SerializeToString,
            app_dot_services_dot_bank__account_dot_bank__account__pb2.BankAccountResponse.FromString,
            options, channel_credentials,
            call_credentials, compression, wait_for_ready, timeout, metadata)
