# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: app/services/bank_account/bank_account.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='app/services/bank_account/bank_account.proto',
  package='',
  syntax='proto2',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n,app/services/bank_account/bank_account.proto\"\x12\n\x10\x42\x61nkAccountEmpty\"\"\n\x14\x42\x61nkAccountIdRequest\x12\n\n\x02id\x18\x01 \x02(\t\"}\n\x17\x42\x61nkAccountNotIdRequest\x12\r\n\x05\x63hase\x18\x01 \x02(\t\x12\x15\n\rbranchAddress\x18\x02 \x02(\t\x12\x17\n\x0f\x63heckingAccount\x18\x03 \x02(\t\x12\x15\n\rroutingNumber\x18\x04 \x01(\t\x12\x0c\n\x04\x62\x61nk\x18\x05 \x01(\t\"\x84\x01\n\x12\x42\x61nkAccountRequest\x12\n\n\x02id\x18\x01 \x02(\t\x12\r\n\x05\x63hase\x18\x02 \x02(\t\x12\x15\n\rbranchAddress\x18\x03 \x02(\t\x12\x17\n\x0f\x63heckingAccount\x18\x04 \x02(\t\x12\x15\n\rroutingNumber\x18\x05 \x01(\t\x12\x0c\n\x04\x62\x61nk\x18\x06 \x01(\t\"?\n\x13\x42\x61nkAccountResponse\x12(\n\x0b\x62\x61nkAccount\x18\x01 \x02(\x0b\x32\x13.BankAccountRequest\"G\n\x1b\x42\x61nkAccountMultipleResponse\x12(\n\x0b\x62\x61nkAccount\x18\x01 \x03(\x0b\x32\x13.BankAccountRequest2\xed\x01\n\x0b\x42\x61nkAccount\x12:\n\x07get_all\x12\x11.BankAccountEmpty\x1a\x1c.BankAccountMultipleResponse\x12\x36\n\x04save\x12\x18.BankAccountNotIdRequest\x1a\x14.BankAccountResponse\x12\x33\n\x06update\x12\x13.BankAccountRequest\x1a\x14.BankAccountResponse\x12\x35\n\x06\x64\x65lete\x12\x15.BankAccountIdRequest\x1a\x14.BankAccountResponse'
)




_BANKACCOUNTEMPTY = _descriptor.Descriptor(
  name='BankAccountEmpty',
  full_name='BankAccountEmpty',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=48,
  serialized_end=66,
)


_BANKACCOUNTIDREQUEST = _descriptor.Descriptor(
  name='BankAccountIdRequest',
  full_name='BankAccountIdRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='BankAccountIdRequest.id', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=68,
  serialized_end=102,
)


_BANKACCOUNTNOTIDREQUEST = _descriptor.Descriptor(
  name='BankAccountNotIdRequest',
  full_name='BankAccountNotIdRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='chase', full_name='BankAccountNotIdRequest.chase', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='branchAddress', full_name='BankAccountNotIdRequest.branchAddress', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='checkingAccount', full_name='BankAccountNotIdRequest.checkingAccount', index=2,
      number=3, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='routingNumber', full_name='BankAccountNotIdRequest.routingNumber', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='bank', full_name='BankAccountNotIdRequest.bank', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=104,
  serialized_end=229,
)


_BANKACCOUNTREQUEST = _descriptor.Descriptor(
  name='BankAccountRequest',
  full_name='BankAccountRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='BankAccountRequest.id', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='chase', full_name='BankAccountRequest.chase', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='branchAddress', full_name='BankAccountRequest.branchAddress', index=2,
      number=3, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='checkingAccount', full_name='BankAccountRequest.checkingAccount', index=3,
      number=4, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='routingNumber', full_name='BankAccountRequest.routingNumber', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='bank', full_name='BankAccountRequest.bank', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=232,
  serialized_end=364,
)


_BANKACCOUNTRESPONSE = _descriptor.Descriptor(
  name='BankAccountResponse',
  full_name='BankAccountResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='bankAccount', full_name='BankAccountResponse.bankAccount', index=0,
      number=1, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=366,
  serialized_end=429,
)


_BANKACCOUNTMULTIPLERESPONSE = _descriptor.Descriptor(
  name='BankAccountMultipleResponse',
  full_name='BankAccountMultipleResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='bankAccount', full_name='BankAccountMultipleResponse.bankAccount', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=431,
  serialized_end=502,
)

_BANKACCOUNTRESPONSE.fields_by_name['bankAccount'].message_type = _BANKACCOUNTREQUEST
_BANKACCOUNTMULTIPLERESPONSE.fields_by_name['bankAccount'].message_type = _BANKACCOUNTREQUEST
DESCRIPTOR.message_types_by_name['BankAccountEmpty'] = _BANKACCOUNTEMPTY
DESCRIPTOR.message_types_by_name['BankAccountIdRequest'] = _BANKACCOUNTIDREQUEST
DESCRIPTOR.message_types_by_name['BankAccountNotIdRequest'] = _BANKACCOUNTNOTIDREQUEST
DESCRIPTOR.message_types_by_name['BankAccountRequest'] = _BANKACCOUNTREQUEST
DESCRIPTOR.message_types_by_name['BankAccountResponse'] = _BANKACCOUNTRESPONSE
DESCRIPTOR.message_types_by_name['BankAccountMultipleResponse'] = _BANKACCOUNTMULTIPLERESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

BankAccountEmpty = _reflection.GeneratedProtocolMessageType('BankAccountEmpty', (_message.Message,), {
  'DESCRIPTOR' : _BANKACCOUNTEMPTY,
  '__module__' : 'app.services.bank_account.bank_account_pb2'
  # @@protoc_insertion_point(class_scope:BankAccountEmpty)
  })
_sym_db.RegisterMessage(BankAccountEmpty)

BankAccountIdRequest = _reflection.GeneratedProtocolMessageType('BankAccountIdRequest', (_message.Message,), {
  'DESCRIPTOR' : _BANKACCOUNTIDREQUEST,
  '__module__' : 'app.services.bank_account.bank_account_pb2'
  # @@protoc_insertion_point(class_scope:BankAccountIdRequest)
  })
_sym_db.RegisterMessage(BankAccountIdRequest)

BankAccountNotIdRequest = _reflection.GeneratedProtocolMessageType('BankAccountNotIdRequest', (_message.Message,), {
  'DESCRIPTOR' : _BANKACCOUNTNOTIDREQUEST,
  '__module__' : 'app.services.bank_account.bank_account_pb2'
  # @@protoc_insertion_point(class_scope:BankAccountNotIdRequest)
  })
_sym_db.RegisterMessage(BankAccountNotIdRequest)

BankAccountRequest = _reflection.GeneratedProtocolMessageType('BankAccountRequest', (_message.Message,), {
  'DESCRIPTOR' : _BANKACCOUNTREQUEST,
  '__module__' : 'app.services.bank_account.bank_account_pb2'
  # @@protoc_insertion_point(class_scope:BankAccountRequest)
  })
_sym_db.RegisterMessage(BankAccountRequest)

BankAccountResponse = _reflection.GeneratedProtocolMessageType('BankAccountResponse', (_message.Message,), {
  'DESCRIPTOR' : _BANKACCOUNTRESPONSE,
  '__module__' : 'app.services.bank_account.bank_account_pb2'
  # @@protoc_insertion_point(class_scope:BankAccountResponse)
  })
_sym_db.RegisterMessage(BankAccountResponse)

BankAccountMultipleResponse = _reflection.GeneratedProtocolMessageType('BankAccountMultipleResponse', (_message.Message,), {
  'DESCRIPTOR' : _BANKACCOUNTMULTIPLERESPONSE,
  '__module__' : 'app.services.bank_account.bank_account_pb2'
  # @@protoc_insertion_point(class_scope:BankAccountMultipleResponse)
  })
_sym_db.RegisterMessage(BankAccountMultipleResponse)



_BANKACCOUNT = _descriptor.ServiceDescriptor(
  name='BankAccount',
  full_name='BankAccount',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=505,
  serialized_end=742,
  methods=[
  _descriptor.MethodDescriptor(
    name='get_all',
    full_name='BankAccount.get_all',
    index=0,
    containing_service=None,
    input_type=_BANKACCOUNTEMPTY,
    output_type=_BANKACCOUNTMULTIPLERESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='save',
    full_name='BankAccount.save',
    index=1,
    containing_service=None,
    input_type=_BANKACCOUNTNOTIDREQUEST,
    output_type=_BANKACCOUNTRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='update',
    full_name='BankAccount.update',
    index=2,
    containing_service=None,
    input_type=_BANKACCOUNTREQUEST,
    output_type=_BANKACCOUNTRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='delete',
    full_name='BankAccount.delete',
    index=3,
    containing_service=None,
    input_type=_BANKACCOUNTIDREQUEST,
    output_type=_BANKACCOUNTRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_BANKACCOUNT)

DESCRIPTOR.services_by_name['BankAccount'] = _BANKACCOUNT

# @@protoc_insertion_point(module_scope)
