# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: app/services/favorite/favorite.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='app/services/favorite/favorite.proto',
  package='',
  syntax='proto2',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n$app/services/favorite/favorite.proto\"\x0f\n\rFavoriteEmpty\"\x1f\n\x11\x46\x61voriteIdRequest\x12\n\n\x02id\x18\x01 \x02(\t\"7\n\x14\x46\x61voriteNotIdRequest\x12\r\n\x05names\x18\x01 \x02(\t\x12\x10\n\x08username\x18\x02 \x02(\t\">\n\x0f\x46\x61voriteRequest\x12\n\n\x02id\x18\x01 \x02(\t\x12\r\n\x05names\x18\x02 \x02(\t\x12\x10\n\x08username\x18\x03 \x02(\t\"6\n\x10\x46\x61voriteResponse\x12\"\n\x08\x66\x61vorite\x18\x01 \x02(\x0b\x32\x10.FavoriteRequest\">\n\x18\x46\x61voriteMultipleResponse\x12\"\n\x08\x66\x61vorite\x18\x01 \x03(\x0b\x32\x10.FavoriteRequest2\xd2\x01\n\x08\x46\x61vorite\x12\x34\n\x07get_all\x12\x0e.FavoriteEmpty\x1a\x19.FavoriteMultipleResponse\x12\x30\n\x04save\x12\x15.FavoriteNotIdRequest\x1a\x11.FavoriteResponse\x12-\n\x06update\x12\x10.FavoriteRequest\x1a\x11.FavoriteResponse\x12/\n\x06\x64\x65lete\x12\x12.FavoriteIdRequest\x1a\x11.FavoriteResponse'
)




_FAVORITEEMPTY = _descriptor.Descriptor(
  name='FavoriteEmpty',
  full_name='FavoriteEmpty',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=40,
  serialized_end=55,
)


_FAVORITEIDREQUEST = _descriptor.Descriptor(
  name='FavoriteIdRequest',
  full_name='FavoriteIdRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='FavoriteIdRequest.id', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=57,
  serialized_end=88,
)


_FAVORITENOTIDREQUEST = _descriptor.Descriptor(
  name='FavoriteNotIdRequest',
  full_name='FavoriteNotIdRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='names', full_name='FavoriteNotIdRequest.names', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='username', full_name='FavoriteNotIdRequest.username', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=90,
  serialized_end=145,
)


_FAVORITEREQUEST = _descriptor.Descriptor(
  name='FavoriteRequest',
  full_name='FavoriteRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='FavoriteRequest.id', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='names', full_name='FavoriteRequest.names', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='username', full_name='FavoriteRequest.username', index=2,
      number=3, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=147,
  serialized_end=209,
)


_FAVORITERESPONSE = _descriptor.Descriptor(
  name='FavoriteResponse',
  full_name='FavoriteResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='favorite', full_name='FavoriteResponse.favorite', index=0,
      number=1, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=211,
  serialized_end=265,
)


_FAVORITEMULTIPLERESPONSE = _descriptor.Descriptor(
  name='FavoriteMultipleResponse',
  full_name='FavoriteMultipleResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='favorite', full_name='FavoriteMultipleResponse.favorite', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=267,
  serialized_end=329,
)

_FAVORITERESPONSE.fields_by_name['favorite'].message_type = _FAVORITEREQUEST
_FAVORITEMULTIPLERESPONSE.fields_by_name['favorite'].message_type = _FAVORITEREQUEST
DESCRIPTOR.message_types_by_name['FavoriteEmpty'] = _FAVORITEEMPTY
DESCRIPTOR.message_types_by_name['FavoriteIdRequest'] = _FAVORITEIDREQUEST
DESCRIPTOR.message_types_by_name['FavoriteNotIdRequest'] = _FAVORITENOTIDREQUEST
DESCRIPTOR.message_types_by_name['FavoriteRequest'] = _FAVORITEREQUEST
DESCRIPTOR.message_types_by_name['FavoriteResponse'] = _FAVORITERESPONSE
DESCRIPTOR.message_types_by_name['FavoriteMultipleResponse'] = _FAVORITEMULTIPLERESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

FavoriteEmpty = _reflection.GeneratedProtocolMessageType('FavoriteEmpty', (_message.Message,), {
  'DESCRIPTOR' : _FAVORITEEMPTY,
  '__module__' : 'app.services.favorite.favorite_pb2'
  # @@protoc_insertion_point(class_scope:FavoriteEmpty)
  })
_sym_db.RegisterMessage(FavoriteEmpty)

FavoriteIdRequest = _reflection.GeneratedProtocolMessageType('FavoriteIdRequest', (_message.Message,), {
  'DESCRIPTOR' : _FAVORITEIDREQUEST,
  '__module__' : 'app.services.favorite.favorite_pb2'
  # @@protoc_insertion_point(class_scope:FavoriteIdRequest)
  })
_sym_db.RegisterMessage(FavoriteIdRequest)

FavoriteNotIdRequest = _reflection.GeneratedProtocolMessageType('FavoriteNotIdRequest', (_message.Message,), {
  'DESCRIPTOR' : _FAVORITENOTIDREQUEST,
  '__module__' : 'app.services.favorite.favorite_pb2'
  # @@protoc_insertion_point(class_scope:FavoriteNotIdRequest)
  })
_sym_db.RegisterMessage(FavoriteNotIdRequest)

FavoriteRequest = _reflection.GeneratedProtocolMessageType('FavoriteRequest', (_message.Message,), {
  'DESCRIPTOR' : _FAVORITEREQUEST,
  '__module__' : 'app.services.favorite.favorite_pb2'
  # @@protoc_insertion_point(class_scope:FavoriteRequest)
  })
_sym_db.RegisterMessage(FavoriteRequest)

FavoriteResponse = _reflection.GeneratedProtocolMessageType('FavoriteResponse', (_message.Message,), {
  'DESCRIPTOR' : _FAVORITERESPONSE,
  '__module__' : 'app.services.favorite.favorite_pb2'
  # @@protoc_insertion_point(class_scope:FavoriteResponse)
  })
_sym_db.RegisterMessage(FavoriteResponse)

FavoriteMultipleResponse = _reflection.GeneratedProtocolMessageType('FavoriteMultipleResponse', (_message.Message,), {
  'DESCRIPTOR' : _FAVORITEMULTIPLERESPONSE,
  '__module__' : 'app.services.favorite.favorite_pb2'
  # @@protoc_insertion_point(class_scope:FavoriteMultipleResponse)
  })
_sym_db.RegisterMessage(FavoriteMultipleResponse)



_FAVORITE = _descriptor.ServiceDescriptor(
  name='Favorite',
  full_name='Favorite',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=332,
  serialized_end=542,
  methods=[
  _descriptor.MethodDescriptor(
    name='get_all',
    full_name='Favorite.get_all',
    index=0,
    containing_service=None,
    input_type=_FAVORITEEMPTY,
    output_type=_FAVORITEMULTIPLERESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='save',
    full_name='Favorite.save',
    index=1,
    containing_service=None,
    input_type=_FAVORITENOTIDREQUEST,
    output_type=_FAVORITERESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='update',
    full_name='Favorite.update',
    index=2,
    containing_service=None,
    input_type=_FAVORITEREQUEST,
    output_type=_FAVORITERESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='delete',
    full_name='Favorite.delete',
    index=3,
    containing_service=None,
    input_type=_FAVORITEIDREQUEST,
    output_type=_FAVORITERESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_FAVORITE)

DESCRIPTOR.services_by_name['Favorite'] = _FAVORITE

# @@protoc_insertion_point(module_scope)
