# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from app.protos import favorite_pb2 as app_dot_services_dot_favorite_dot_favorite__pb2


class FavoriteStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.get_all = channel.unary_unary(
                '/Favorite/get_all',
                request_serializer=app_dot_services_dot_favorite_dot_favorite__pb2.FavoriteEmpty.SerializeToString,
                response_deserializer=app_dot_services_dot_favorite_dot_favorite__pb2.FavoriteMultipleResponse.FromString,
                )
        self.save = channel.unary_unary(
                '/Favorite/save',
                request_serializer=app_dot_services_dot_favorite_dot_favorite__pb2.FavoriteNotIdRequest.SerializeToString,
                response_deserializer=app_dot_services_dot_favorite_dot_favorite__pb2.FavoriteResponse.FromString,
                )
        self.update = channel.unary_unary(
                '/Favorite/update',
                request_serializer=app_dot_services_dot_favorite_dot_favorite__pb2.FavoriteRequest.SerializeToString,
                response_deserializer=app_dot_services_dot_favorite_dot_favorite__pb2.FavoriteResponse.FromString,
                )
        self.delete = channel.unary_unary(
                '/Favorite/delete',
                request_serializer=app_dot_services_dot_favorite_dot_favorite__pb2.FavoriteIdRequest.SerializeToString,
                response_deserializer=app_dot_services_dot_favorite_dot_favorite__pb2.FavoriteResponse.FromString,
                )


class FavoriteServicer(object):
    """Missing associated documentation comment in .proto file."""

    def get_all(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def save(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def update(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def delete(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_FavoriteServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'get_all': grpc.unary_unary_rpc_method_handler(
                    servicer.get_all,
                    request_deserializer=app_dot_services_dot_favorite_dot_favorite__pb2.FavoriteEmpty.FromString,
                    response_serializer=app_dot_services_dot_favorite_dot_favorite__pb2.FavoriteMultipleResponse.SerializeToString,
            ),
            'save': grpc.unary_unary_rpc_method_handler(
                    servicer.save,
                    request_deserializer=app_dot_services_dot_favorite_dot_favorite__pb2.FavoriteNotIdRequest.FromString,
                    response_serializer=app_dot_services_dot_favorite_dot_favorite__pb2.FavoriteResponse.SerializeToString,
            ),
            'update': grpc.unary_unary_rpc_method_handler(
                    servicer.update,
                    request_deserializer=app_dot_services_dot_favorite_dot_favorite__pb2.FavoriteRequest.FromString,
                    response_serializer=app_dot_services_dot_favorite_dot_favorite__pb2.FavoriteResponse.SerializeToString,
            ),
            'delete': grpc.unary_unary_rpc_method_handler(
                    servicer.delete,
                    request_deserializer=app_dot_services_dot_favorite_dot_favorite__pb2.FavoriteIdRequest.FromString,
                    response_serializer=app_dot_services_dot_favorite_dot_favorite__pb2.FavoriteResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'Favorite', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Favorite(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def get_all(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Favorite/get_all',
            app_dot_services_dot_favorite_dot_favorite__pb2.FavoriteEmpty.SerializeToString,
            app_dot_services_dot_favorite_dot_favorite__pb2.FavoriteMultipleResponse.FromString,
            options, channel_credentials,
            call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def save(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Favorite/save',
            app_dot_services_dot_favorite_dot_favorite__pb2.FavoriteNotIdRequest.SerializeToString,
            app_dot_services_dot_favorite_dot_favorite__pb2.FavoriteResponse.FromString,
            options, channel_credentials,
            call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def update(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Favorite/update',
            app_dot_services_dot_favorite_dot_favorite__pb2.FavoriteRequest.SerializeToString,
            app_dot_services_dot_favorite_dot_favorite__pb2.FavoriteResponse.FromString,
            options, channel_credentials,
            call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def delete(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Favorite/delete',
            app_dot_services_dot_favorite_dot_favorite__pb2.FavoriteIdRequest.SerializeToString,
            app_dot_services_dot_favorite_dot_favorite__pb2.FavoriteResponse.FromString,
            options, channel_credentials,
            call_credentials, compression, wait_for_ready, timeout, metadata)
